// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkflowEngine.Infrastructure.Data;

#nullable disable

namespace WorkflowEngine.Infrastructure.Migrations
{
    [DbContext(typeof(WorkflowEngineDbContext))]
    [Migration("20250522044647_AddNodeConnections")]
    partial class AddNodeConnections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("WorkflowEngine.Infrastructure.Entities.NodeConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FromNodeInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromPortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ToNodeInstanceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToPortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FromNodeInstanceId");

                    b.HasIndex("ToNodeInstanceId");

                    b.ToTable("NodeConnections");
                });

            modelBuilder.Entity("WorkflowEngine.Infrastructure.Entities.NodeInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PositionX")
                        .HasColumnType("REAL");

                    b.Property<double>("PositionY")
                        .HasColumnType("REAL");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("NodeInstances");
                });

            modelBuilder.Entity("WorkflowEngine.Infrastructure.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("WorkflowEngine.Infrastructure.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorkflowEngine.Infrastructure.Entities.NodeConnection", b =>
                {
                    b.HasOne("WorkflowEngine.Infrastructure.Entities.NodeInstance", "FromNode")
                        .WithMany("OutgoingConnections")
                        .HasForeignKey("FromNodeInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkflowEngine.Infrastructure.Entities.NodeInstance", "ToNode")
                        .WithMany("IncomingConnections")
                        .HasForeignKey("ToNodeInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromNode");

                    b.Navigation("ToNode");
                });

            modelBuilder.Entity("WorkflowEngine.Infrastructure.Entities.NodeInstance", b =>
                {
                    b.HasOne("WorkflowEngine.Infrastructure.Entities.Project", "Project")
                        .WithMany("NodeInstances")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("WorkflowEngine.Infrastructure.Entities.Project", b =>
                {
                    b.HasOne("WorkflowEngine.Infrastructure.Entities.User", "Owner")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("WorkflowEngine.Infrastructure.Entities.NodeInstance", b =>
                {
                    b.Navigation("IncomingConnections");

                    b.Navigation("OutgoingConnections");
                });

            modelBuilder.Entity("WorkflowEngine.Infrastructure.Entities.Project", b =>
                {
                    b.Navigation("NodeInstances");
                });

            modelBuilder.Entity("WorkflowEngine.Infrastructure.Entities.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
